### PR TITLE
Mina changing search

### PR DESCRIPTION
**Pull request by minasamadi**
Added validation of Scale and Stakeholder to searchMethod
Changed searchMethod (the part related to stakeholder) due to change of stakeholder's type to array
converting 2 custom validator to method because of reusability and changed add and update method based on that
Everything is tested and still I see some errors related to swagger.

if any changes need, please let me know

### CODE REVIEW

**Review by fra2404 — CHANGES_REQUESTED** [review]
Everything works, whether to do it with AND or OR in the case of multiples has to be decided. Then I would insert a validator on the other fields and not give the possibility to pass any other values than the ones we want. If I now search for ‘hello’: ‘hello’ it goes ahead and returns the values it finds not considering the filters in the body, I would make sure not to accept other fields other than the ones we want there, considering that they may not even be considered. Otherwise perfect

**Comment by minasamadi** [comment]
Validation for architecturalScale added. 
The part for searching based on this field added to search method.

**Review by fra2404 — CHANGES_REQUESTED** [review]
The things I had written down to solve have not been solved, the search for architecturalScale does not work. If I search 1:100, it returns all the values that have the searched value going up, so even 1:1000, 1:10000 and so on. For this it must be the exact value, not contained in

**Comment by minasamadi** [comment]
I changed the search method, now it looks for the exact architectural scale.
during testing I understood that in update method if we changed the scale to "ARCHITECTURAL" but do not insert "architecturalScale" value for that, it updates data without any error, while in addDocument it was checked. So if you want you can also test it.

**Review by fra2404 — CHANGES_REQUESTED** [review]
Nothing change. The problem persists, if i search 1:100 i obtain also the documents with 1:1000. Same error of before for the stakeholders search

**Review by fra2404 — COMMENTED** [review]
Given these errors I didn't check further

**Review by fra2404 — CHANGES_REQUESTED** [review]
You still don't check the body key and for stakeholder when we search for a combination we want exactly that ne, but when we search for the single all those that contain it

**Comment by minasamadi** [comment]
I thought searching only one element is the same as multiple items and it should looks for the exact one. I changed the search method for stakeholder.
now for single item it looks for any combination in which the item exist, and for multiple items looks for the exact combination.
About the key, I should talk to you and I did nothing

**Comment by minasamadi** [comment]
Checking the keys was something related to search method and it did not happen just for scale or stakeholder.
And as the method was not written by me, I had not checked it. Now it is added to validation.
Check please and if anything else needed let me know.

**Review by fra2404 — APPROVED** [review]
Ok

**Pull request merged**
