### PR TITLE
Updated different parts rekated to stakeholder

### PR DESCRIPTION
**Pull request by minasamadi**
The stakeholders field has been updated to be an array that holds predefined static values, rather than input values
changes are based on the following:
adding Enum
changing swagger
changing Interfaces related to document
changing schemas of document
updating validators of add and update document

I tested using postman both add and update document with different states for "stakeholder" fields
I also tried to update "search" method but I could not.

### CODE REVIEW

**Review by fra2404 — CHANGES_REQUESTED** [review]
Error inserting ArchitectureFirms and RegionalAuthority. To be fixed also the interface, even if now it runs is better have a good declaration, so insert the declaration of the array for the stakeholders

**Comment by minasamadi** [comment]
The first part solved.
But for the second part I just did not get what you mean, and I do not know what I should do. I also could not find something similar for other Enums to get help from them.

**Review by fra2404 — APPROVED** [review]
I fixed the problems for the second part. Now it works also the firts one. Currently this approved, but since the problem with the search persists, the task is to be continued. Change the search so that it searches by stakeholder, make the fields fixed there as well, and you must search so that you see inside the stakeholder array of each document

**Review by fra2404 — COMMENTED** [review]
Wrong swagger

**Review by fra2404 — CHANGES_REQUESTED** [review]
The search still works, but if we now have fixed fields for stakeholders, it is good to have the same fixed fields during the search as well, so we need to insert a validator there. That is the change to be made. Then the swagger must be adapted

**Review by fra2404 — APPROVED** [review]

**Review by fra2404 — APPROVED** [review]

**Pull request merged**
