### PR TITLE
Mina stakeholder changes

### PR DESCRIPTION
**Pull request by minasamadi**
I tried to check everything related to stakeholder and updated whatever needed after moving it from enum to DB collection.
Added:
    New schema, interface, controller, validator, route, service, and error handling for stakeholder 
Updated:
   Stakeholder validation in other validator files.
  documentService to include stakeholder existence checks and return values.

I tested all methods after changes.
if there is any problem, please let me know

### CODE REVIEW

**Review by fra2404 — CHANGES_REQUESTED** [review]
There were some things that didn't work and that i changed. One of them didn't make sense at all. The code basically works, very well. But if I try to load an array with the sqme id twice it makes me do it. It is important that each stakeholder can be put only once. Swagger as usual wrong

**Comment by minasamadi** [comment]
I added validation for update and create document methods. both in validator and service files.
I did nit change swagger, because I do not know how to do it and what the problem is

**Review by fra2404 — CHANGES_REQUESTED** [review]
The problem persists. I think that you didn't push

**Comment by minasamadi** [comment]
I have done

**Review by fra2404 — APPROVED** [review]
Ok

**Pull request merged**
