### PR TITLE
Mina method save media metadata

### PR DESCRIPTION
**Pull request by minasamadi**
I did both "saving metadata of media" and also "updating it based on CDN output", in this branch.

As I could not find type in CDN output I wrote a small method for recognizing it from mimeType.
And the only field that is updated now after CDN responses to BE, is pages.

### CODE REVIEW

**Review by fra2404 — CHANGES_REQUESTED** [review]
It cannot be tested due to a start-up error. Should be a problem with the swagger written.

/server/node_modules/swagger-jsdoc/src/specification.js:253
      docWithErr.errors.forEach((error, index) => {
                        ^
TypeError: Cannot read properties of undefined (reading 'cstNode')

**Review by fra2404 — CHANGES_REQUESTED** [review]
Same error. Start the validator of mongo and not the validator of express. If you try to insert as pages a string it pass and the call is blocked by mongo, is an error

**Review by fra2404 — CHANGES_REQUESTED** [review]
When I send the size this is not updated. It is only updated if I also send the pages, but that is an optional field. 
The code is heterogeneous, errors are handled differently from the rest of the code, as is validation, which throws an internal error and does not pass through the middleware in one case. The swagger is not aligned to the latest changes, the size in update is not accepted, when it is a mandatory parameter

**Comment by minasamadi** [comment]
updateMedia methos is updated and tested. Now with and without inserting page, size is updated.
"error.ts" file was updated before for Media. and now updated also on this branch and used in updateMedia method.
The swagger of updateMedia method updated based on last changes.
All possible conditions tested by postman.

**Review by fra2404 — APPROVED** [review]
Ok

**Review by fra2404 — APPROVED** [review]

**Pull request merged**
