### PR TITLE
Mariam dev

### PR DESCRIPTION
**Pull request by mariamtelly**
Here it is. I am sorry for being late. But I had bugs I was trying to correct.
Now we can draw and save areas.

### CODE REVIEW

**Review by Paolino01 — CHANGES_REQUESTED** [review]
Code quality is fine. See what I wrote on Telegram about the filters

**Review by fra2404 — CHANGES_REQUESTED** [review]
In the coordinates in one case you changed from area to polygon and in anothere vice versa. It must be unified. Why did you make this change? Area is not good because mongo does not interpet it as a geojson. You don't have to push your .env.local file because it also changes ours and we have the database locally. The package-lock.json must not be pushed

**Review by fra2404 — CHANGES_REQUESTED** [review]
Also, you didn't validate the coordinates during the earch, You can enter any value. This is not good

**Comment by mariamtelly** [comment]
I have made the changes you request. But for this part " in one case you changed from area to polygon and in anothere vice versa", I could not see what you were talking about, I have put "Polygon" everywhere. I have changed because I had noticed inconsistencies.

**Review by fra2404 — APPROVED** [review]
Backend OK. Paolo can you check frontend

**Review by fra2404 — COMMENTED** [review]
Paolo if you can remove .env.local file even if now with this merge we'll have that file in git ignore

**Pull request merged**
