### PR TITLE
Mina changing doc type

### PR DESCRIPTION
**Pull request by minasamadi**
I implemented the part related to documentType.  Added what was needed for this part (schema, validator, interface, service, route, error handling, ...) and changed whatever was needed (methods of document, interfaces, validators)

While I was testing, I got that searching by stakeholder is not working by text. 
It was ok by id like :
{ "stakeholders" : ["67595fffb0dc20817d2022f2"]}
So I also changed that part in search section and add a new method for it "fetchStakeholdersForSearch". you can also check this.
I also changes type of stakeholder and doctype in IDocumentFilters, please also check this.

I know that based on some changes maybe I should also update the swaggers, or even write new one. But I really do not know how to do that. As most of the time you said they have problem I have not changed old ones.

If any changes needed, let me know.

### CODE REVIEW

**Review by fra2404 — CHANGES_REQUESTED** [review]
It's an error have the camelcase inside the API. Then, why if you use a service for documentType did you insert this in service of the documents and not in that one for the documentType?
When you want to obtain the value of the type remove the version, creationDate and updateDate, as i modified in the previous merge request for the stakeholders.
You made the same error did for the stakeholder, it doesn't make sense have type new and then newDocumentType for the request

**Comment by minasamadi** [comment]
I updated "documentType" to "document-type" as you suggested. However, in programming, I think an error usually refers to something that prevents the code from functioning correctly. In this case, using camelCase doesn’t cause any issues.

I also removed the version, creationDate and updateDate in "fetchDocumentTypesForSearch", "fetchStakeholdersForSearch" 

Methods of documentType, media and stakeholders moved to their own service files.

for the last part, I think I just did the same as stakeholder and I could not find where you mean.

**Review by fra2404 — CHANGES_REQUESTED** [review]
It runs, i made a small change. But it's wrong the search. It doens't make sense that once that we have a list of stakeholder and types we search by name and not by their id. So it's important search the document by the id of the stakeholder and by the id of the types, and not by the name. It's more safe

**Comment by minasamadi** [comment]
Search is done based on id of stakeholder and documentType

**Review by fra2404 — APPROVED** [review]
Ok

**Pull request merged**
